// Mocks generated by Mockito 5.4.6 from annotations
// in nasa_astronomy_app/test/data/datasources/today_apod/today_apod_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nasa_astronomy_app/data/datasources/network/network_checker.dart'
    as _i5;
import 'package:nasa_astronomy_app/data/datasources/today_apod/today_apod_datasource.dart'
    as _i3;
import 'package:nasa_astronomy_app/data/models/apod_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApodModel_0 extends _i1.SmartFake implements _i2.ApodModel {
  _FakeApodModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodayApodDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodayApodDatasource extends _i1.Mock
    implements _i3.TodayApodDatasource {
  @override
  _i4.Future<_i2.ApodModel> fetchTodayApod() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTodayApod, []),
            returnValue: _i4.Future<_i2.ApodModel>.value(
              _FakeApodModel_0(this, Invocation.method(#fetchTodayApod, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ApodModel>.value(
              _FakeApodModel_0(this, Invocation.method(#fetchTodayApod, [])),
            ),
          )
          as _i4.Future<_i2.ApodModel>);
}

/// A class which mocks [NetworkChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkChecker extends _i1.Mock implements _i5.NetworkChecker {
  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
